services:
  - type: web
    name: react-login-client
    env: static
    staticPublishPath: client/dist
    buildCommand: cd client && npm install && npm run build

  - type: web
    name: react-login-server
    env: node
    buildCommand: cd server && npm install
    startCommand: node server/express.js
